### ISSUE TITLE
Notifications showing up as "shared" rather than "liked" in popover view

### ISSUE THREAD

**Issue by gaelicgalpal** [enchanted-sword/ch-utils#10]
**Describe the bug**
Any "x liked your posts" notifications in the notifications popover view appear as "x shared your post" instead, though the correct icon is still displayed next to them.

**To Reproduce**
1. Enable Notifications in Popover View
2. Open the notifications popover view

**Expected behavior**
The notifications should be labeled as "x liked your post" instead of "x shared your post.

**Screenshots**
![image](https://github.com/enchanted-sword/ch-utils/assets/81559286/984c39a6-c172-4cdf-aadd-37b7ffe96d72)

**Device information (please complete the following information):**
 - OS: Windows 10
 - Version: Firefox 127.0.2 (64-bit)
 
**Additional context**
I know this isn't a huge bug, but I thought I'd bring it up, since I had been getting worried people were able to share posts I had locked sharing on.

**Comment by enchanted-sword** [comment]
It's already been fixed for the next release, thanks for reporting it though!
