### ISSUE TITLE
There's no way to get a permalink to a draft, if you have 'show comments under posts' enabled

### ISSUE THREAD

**Issue by Alloyed** [enchanted-sword/ch-utils#11]
**To Reproduce**
1. create a draft post
3. enable "Show comments under posts"
4. Go to drafts
5. Attempt to find the permalink for that draft. screenshot attached

**Expected behavior**
on published posts, there's a timestamp you can click to go to the post. this was never published, so no timestamp. you can also click on the "comments", normally, to go to the link + '#comments'. disabled by the extension. arguably this is more of a feature request for a permalink button? i guess, which would solve this loss of functionality. 

**Screenshots**

![image](https://github.com/user-attachments/assets/b375f7d8-737a-4248-b1d5-4ea6e670cbf4)

**Comment by enchanted-sword** [comment]
You can copy the link for a draft in either of these spots:
![image](https://github.com/user-attachments/assets/41c043fb-fc8f-4f41-ac45-457f9348387a)
The expand comments button is still a link, so you can right-click on it to bring up the context menu or ctrl-left-click to open it in a new tab.
