### ISSUE TITLE
Display Post Source Code desyncing on long collapsable threads

### ISSUE THREAD

**Issue by Mynotaurus** [enchanted-sword/ch-utils#2]
**Describe the bug**
Whenever a long post chain shows with a "show X posts" button, the collapsed posts aren't seen, causing them to not load with "view source code" buttons, and for the next uncollapsed posts to show incorrectly indexed source code from the collapsed ones.

**To Reproduce**
1. Use Display Post Source Code
2. Turn on "hide middle of long threads by default" in your cohost settings
3. Use it on any post in a collapsed thread of posts (excluding the first one in the thread, which always loads fine) that appears on **your dashboard or a user's timeline**, as long threads do not seem to collapse when viewed as a direct link to them and therefore don't run into this issue

**Expected behavior**
Buttons should probably appear when threads are uncollapsed and new posts are revealed, and posts later down the thread should show the correct source code without indexing collapsed or previously-collapsed posts.

**Screenshots**
![image](https://github.com/enchanted-sword/ch-utils/assets/46263022/ca0762fd-ea9f-4f81-9a02-66b2e99b419a)

**Device information (please complete the following information):**
 - OS: Windows 10
 - Version: Firefox 126.0

**Additional context**
N/A

**Comment by enchanted-sword** [comment]
Switched the mutation function to operate on individual posts in threads thread as opposed to having it run exactly once per thread, so it should now catch whenever collapsed posts in a thread are expanded.

![image](https://github.com/enchanted-sword/ch-utils/assets/81981111/04e3f62f-07ff-4d78-8fef-15a2f216bba0)

**Comment by enchanted-sword** [comment]
Should be fixed in v1.2.2!
