### ISSUE TITLE
18+ images forced open

### ISSUE THREAD

**Issue by easrng** [enchanted-sword/ch-utils#22]
**Describe the bug**
I can't close 18+ images chutils autoopens on my nsfw pages

**To Reproduce**
1. Set chutils to autoexpand 18+ posts
2. Try to close an 18+ post

**Expected behavior**
The post content is hidden

**Device information (please complete the following information):**
 - OS: Android
 - Version: Firefox 129

**Comment by enchanted-sword** [comment]
Oops, I forgot to request the designer of that feature add a custom attribute to prevent posts from being processed more than once. It's an easy enough fix, thankfully.

**Comment by enchanted-sword** [comment]
fixed in 1bebae2c978e786c5cc1a60cc8f1f2f6c3e124f4
