### ISSUE TITLE
Post preview breaks when escaping markdown

### ISSUE THREAD

**Issue by moss-weaver** [enchanted-sword/ch-utils#23]
**Describe the bug**
Live post preview stops updating when a markdown character is escaped

**To Reproduce**
1. Enable chutils post preview
2. Start writing a new post
3. In the body text include the sequence `\*`
4. Keep typing
5. Notice that the live preview has stopped updating

**Expected behavior**
Post preview keeps updating, even if the post contains escaped characters

**Screenshots**
![image](https://github.com/user-attachments/assets/7b057c1f-c749-4af9-9a17-c09e9fc97bcb)

**Device information (please complete the following information):**
 - OS: Fedora 39
 - Version: Firefox 127.0.2 (64-bit)

**Comment by enchanted-sword** [comment]
fixed in 3585cc9
