### ISSUE TITLE
Header like button

### ISSUE THREAD

**Issue by Zuthal** [enchanted-sword/ch-utils#24]
**Is your feature request related to a problem? Please describe.**
When you see a long chain of posts, and want to like all of them (because they are all good posts), you have to individually open each post, which is a bit annoying.

**Describe the solution you'd like**
Add a like button to the right edge of the header bar that contains the username of the poster, for posts that are not standalone or the bottommost post in a repost chain

**Additional context**
This already exists [as a userscript](https://cohost.org/cefqrn/post/1430390-header-buttons-users), but having it integrated into chutils would still be good I think.

**Comment by enchanted-sword** [comment]
definitely doable, there's even already a system in place to add buttons to the individual headers. i could also add the share buttons as well.

**Comment by Zuthal** [comment]
Yeah, I know the "view post source code" function already adds a button to each header. And yeah, the share buttons would probably be useful for some as well!

**Comment by enchanted-sword** [comment]
Added in 5b98e5b8cafc199a9473bc0c74bb9327a1728b9b!
![image](https://github.com/user-attachments/assets/614153ee-6569-445c-804b-360390b6ac79)
