### ISSUE TITLE
Post-specific buttons stop appearing after 4 posts.

### ISSUE THREAD

**Issue by wheelsbot7** [enchanted-sword/ch-utils#5]
Post-specific buttons stop appearing after 4 posts.

Whenever I transition to a new page, the first 4 posts have the comment dropdown and view source buttons like normal, but the rest of the posts don't have them. It sometimes happens after 5 or 6 posts, but I'm unsure what causes it to do that. 

Here's a screenshot of the same post twice. One with the expected buttons, one without. 
![firefox_saWWbrIWbH](https://github.com/enchanted-sword/ch-utils/assets/23087147/bc62eaa3-0dc5-4d48-bb38-7459339d2eb9)

 - OS: Windows 10
 - Version Firefox 126.0

**Comment by wheelsbot7** [comment]
Update: I disabled custom timestamps and the buttons returned.

**Comment by enchanted-sword** [comment]
I just checked, and while a malformed JSON syntax invokes the fallback as expected, an invalid locale value in the timestamp override field throws a luxon-specific error that seems to also be halting MutationObserver updates to other modules. There was an extra singlequote in the default value that I didn't notice until after the update went live, so if you set it to a valid value such as `{ "locale":"en" }` or just leave that field empty it should work as expected. I'll fix the fallback for that today.

**Comment by enchanted-sword** [comment]
Should be fixed in v1.3.1
