### ISSUE TITLE
Appearance of dropdown comments does not match comments on a post's page

### ISSUE THREAD

**Issue by foggles17** [enchanted-sword/ch-utils#6]
**Describe the bug**
When you use the "X comments + Y on shared posts" dropdown to see comments without going to a post's page, the formatting does not match the standard comment formatting, specifically when they use linebreaks.

**To Reproduce**
1. go to cohost.org
2. use the "X comments + Y on shared posts" dropdown
3. find a comment originally written with multiple lines

**Expected behavior**
A single line break in a comment's source normally results in a line break when the comment is displayed.

**Screenshots**
how it appears in the comments dropdown on my timeline:
![image](https://github.com/enchanted-sword/ch-utils/assets/11620778/92797fe7-54d9-4a83-9d8a-31572f75d28c)

how it appears on the post's page:
![image](https://github.com/enchanted-sword/ch-utils/assets/11620778/ef870d81-dc80-4410-95d7-6dc272c488f5)

**Device information:**
 - OS: Windows 10
 - Version: Firefox 126.0.1 (64-bit)

**Comment by enchanted-sword** [comment]
Whoops, looks like the wrapper wasn't set to preserve whitespace.

**Comment by enchanted-sword** [comment]
fixed in 6aff83e and live in v1.3.2
