### ISSUE TITLE
visiting your own page with post filtering on hides all posts

### ISSUE THREAD

**Issue by quwyou** [enchanted-sword/ch-utils#8]
**Describe the bug**
Visiting your own page with post filtering on hides all posts

**To Reproduce**
1. Enable "Post Filtering"
2. Check "hide your own posts"
3. Navigate to your own profile

**Expected behavior**
I would expect post filtering to make an exception for your own posts when you are on your own profile

**Screenshots**
![image](https://github.com/enchanted-sword/ch-utils/assets/57704977/414bd000-a4f6-4cd2-9b26-01c957bbccf3)

**Device information (please complete the following information):**
 - OS: Windows 10
 - Version: Firefox 127.0

**Additional context**
I'm not sure if this is technically a bug, but the behavior seems unintended (or at least counter-intuitive).

**Comment by enchanted-sword** [comment]
Yeah, it probably shouldn't do that

**Comment by enchanted-sword** [comment]
Should be fixed in dde18890e4f6194a5c83926c9cd89e0f6a753367
