### ISSUE TITLE
Opening the Share Post popover menu shunts you back to the top of the page when Follower Page Tweaks is enabled

### ISSUE THREAD

**Issue by Amphobet** [enchanted-sword/ch-utils#9]
**Describe the bug**
If you reshare a post on your timeline while Follower Page Tweaks is enabled, you are scrolled back up to the top of the page.

**To Reproduce**
1. Enable Follower Page Tweaks
2. Visit timeline page and scroll down
3. Reshare a post
4. You are now back at the top of the page.

**Expected behavior**
Resharing a post should not change your location on the page.

**Device information (please complete the following information):**
 - OS: Pop!_OS 22.04 LTS
 - Firefox 127.0 (64-bit)

**Comment by enchanted-sword** [comment]
Already fixed for the next update
